# Generated by Django 6.0.2 on 2026-02-26 07:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receptions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reception',
            name='current_patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_call', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='reception',
            name='is_available',
            field=models.BooleanField(default=False, verbose_name="Bo'sh / Band"),
        ),
        migrations.AddField(
            model_name='reception',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Smenada / Smenada emas'),
        ),
    ]
