# Generated by Django 6.0.2 on 2026-02-26 06:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_hospital_hospitalimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='departments',
            field=models.ManyToManyField(related_name='hospitals', to='hospitals.department'),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='director',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_hospital', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='hospitalimage',
            name='image',
            field=models.ImageField(upload_to='hospitals/photos/'),
        ),
    ]
