# Generated by Django 6.0.2 on 2026-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0003_alter_hospital_address_alter_hospital_departments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hospitals/photos/'),
        ),
        migrations.DeleteModel(
            name='HospitalImage',
        ),
    ]
