# Generated by Django 6.0.2 on 2026-02-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
